server {
    listen 80;
    server_name nirwarna-garage.web.id www.nirwarna-garage.web.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost nirwarna-garage.web.id www.nirwarna-garage.id;
    root /var/www/html/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/alprint.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nirwarna-garage.web.id/privkey.pem;

    # Log file (opsional tapi sangat disarankan buat nyari bug)
    access_log /var/log/nginx/alprint.access.log;
    error_log /var/log/nginx/alprint.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bagian pemrosesan PHP yang sudah dibersihkan
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000; # Pastikan container/service bernama 'app' bisa diakses
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 300;
        fastcgi_buffering off;
    }
}